### ISSUE TITLE
How to update starters

### ISSUE THREAD

**Issue by birkir** [ueno-llc/template-www#1]
### Gatsby
_https://github.com/ueno-llc/ueno-gatsby-starter_

Pulling updates from `template-www`

```bash
git submodule update --init --force --remote
git add .
git commit -m "Updated latest template-www"
```

——

### NextJS
_https://github.com/ueno-llc/create-ueno-app_

Pulling updates from `template-www`

```bash
git submodule update --init --force --remote
git add .
git commit -m "Updated latest template-www"
```

Publishing new version of the package

```bash
npm version [TYPE]
git push master --tags
npm publish
```

——

### create-react-app
_https://github.com/ueno-llc/create-react-app_

Pulling updates from `template-www`

```bash
git submodule update --init --force --remote
git add .
git commit -m "Updated latest template-www"
```

Publishing new version of the package

```bash
yarn lerna publish --scope="@ueno/react-scripts"
```

**Comment by jeremybarbet** [comment]
### First time using submodules

Run this command at the root of each folder (gatsby/next/cra)

```bash
git submodule sync
git submodule init
git submodule update
```
